# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
# AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?
BaseDeliveryFee.create!()
Restaurant.create!(name: "Ember & Tide", open_status: 1, address:  "341 Water Street, Vancouver, BC V6B 1B8", description: "Nestled in the heart of Vancouver’s historic Gastown district, Ember & Tide is a refined yet inviting restaurant that blends the warmth of fire-kissed cuisine with the delicate flavors of the Pacific Northwest. With an open-concept kitchen showcasing a wood-fired grill, fresh seafood bar, and seasonal farm-to-table ingredients, the restaurant offers a sophisticated yet relaxed atmosphere where diners can experience the essence of the West Coast. Floor-to-ceiling windows provide a stunning view of the waterfront, while the rustic-modern décor—featuring reclaimed wood, ambient lighting, and oceanic accents—creates a cozy yet upscale dining experience.\r\n\r\n(604) 555-4823", daysopen: ["", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"], subtitle: "Seafood", city: "Vancouver", slug: "ember-tide")
Dish.create!(name: "Grilled Octopus", description: "Tender octopus, charred to perfection on the wood-fired grill, served with a tangy lemon vinaigrette and fresh herbs.", restaurant_id: 1, quantity: "0", meal_type: "MEAT", dietary: nil, price: "43", image_url: "https://picsum.photos/340/335/?random", image_url2: "https://picsum.photos/340/335/?random", gf: true, df:false, vg: false, gfo: false, dfo: false, vgo: false)
Subselection.create!(name: "Full Plank", description: "dinner sized portion", price: "43", dietary: nil, meal_type: "MEAT", dish_id: 1, restaurant_id: 1, gf: true, df: false, vg: false, gfo: false, dfo: false, vgo: false, serves:1)
OpeningHour.create!(restaurant_id: 1, opens: "2000-01-01 02:00:00.000000000 +0000",closes: "2000-01-01 23:00:00.000000000 +0000")

Restaurant.create!(name: "The Alder Room", open_status: 1, address: "525 Granville Street, Vancouver, BC V6C 1X6", description: "A modern bistro inspired by the lush forests of British Columbia, The Alder Room focuses on locally foraged ingredients and contemporary Canadian cuisine. The interior features natural wood tones, cozy candlelight, and an inviting open kitchen.", daysopen: ["", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"], subtitle: "Canadian", city: "Vancouver", slug: "the-alder-room")
Dish.create!(name: "Cedar-Smoked Duck Breast", description: "Locally sourced duck breast smoked over cedar, served with Saskatoon berry reduction and roasted root vegetables.", restaurant_id: 2, quantity: "0", meal_type: "MEAT", dietary: nil, price: "39", image_url: "https://picsum.photos/340/335/?random", gf: true, df: false, vg: false, gfo: false, dfo: false, vgo: false)
Subselection.create!(name: "Half Portion", description: "Smaller serving with lighter sides", price: "22", dietary: nil, meal_type: "MEAT", dish_id: 2, restaurant_id: 2, gf: true, df: false, vg: false, gfo: false, dfo: false, vgo: false, serves: 1)
OpeningHour.create!(restaurant_id: 2, opens: "2000-01-01 02:00:00.000000000 +0000", closes: "2000-01-01 23:00:00.000000000 +0000")

Restaurant.create!(name: "Harbour & Vine", open_status: 1, address: "872 Davie Street, Vancouver, BC V6Z 2S5", description: "A stylish yet casual wine bar and eatery, Harbour & Vine specializes in West Coast tapas and local wines. With its intimate ambiance and eclectic small plates, it’s a perfect spot for an evening out in the city.", daysopen: ["", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"], subtitle: "Tapas & Wine", city: "Vancouver", slug: "harbour-vine")
Dish.create!(name: "BC Spot Prawn Ceviche", description: "Fresh BC spot prawns marinated in citrus juices, served with avocado, jalapeño, and crisp plantain chips.", restaurant_id: 3, quantity: "0", meal_type: "SEAFOOD", dietary: nil, price: "28", image_url: "https://picsum.photos/340/335/?random", gf: true, df: true, vg: false, gfo: false, dfo: false, vgo: false)
Subselection.create!(name: "Extra Chips", description: "Additional plantain chips for dipping", price: "5", dietary: nil, meal_type: "SNACK", dish_id: 3, restaurant_id: 3, gf: true, df: true, vg: true, gfo: false, dfo: false, vgo: false, serves: 1)
OpeningHour.create!(restaurant_id: 3, opens: "2000-01-01 02:00:00.000000000 +0000", closes: "2000-01-01 23:00:00.000000000 +0000")

Restaurant.create!(name: "Cypress & Co.", open_status: 1, address: "1347 Robson Street, Vancouver, BC V6E 1C6", description: "Cypress & Co. reimagines classic comfort food with a gourmet twist. Using locally sourced ingredients, this trendy eatery is known for its playful takes on nostalgic dishes and inventive cocktails.", daysopen: ["", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"], subtitle: "Modern Comfort", city: "Vancouver", slug: "cypress-co")
Dish.create!(name: "Truffle Mac & Cheese", description: "Rich and creamy mac & cheese infused with black truffle and aged cheddar, topped with a crispy panko crust.", restaurant_id: 4, quantity: "0", meal_type: "VEGETARIAN", dietary: nil, price: "24", image_url: "https://picsum.photos/340/335/?random", gf: false, df: false, vg: true, gfo: true, dfo: false, vgo: true)
Subselection.create!(name: "Gluten-Free Pasta", description: "Made with gluten-free elbow pasta", price: "3", dietary: nil, meal_type: "VEGETARIAN", dish_id: 4, restaurant_id: 4, gf: true, df: false, vg: true, gfo: true, dfo: false, vgo: true, serves: 1)
OpeningHour.create!(restaurant_id: 4, opens: "2000-01-01 02:00:00.000000000 +0000", closes: "2000-01-01 23:00:00.000000000 +0000")
